name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # ✅ Dart 3.7.2 is bundled

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Unit & Widget Tests
        run: flutter test

      - name: Run Integration Tests
        run: flutter test integration_test/
